spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/neratama_db
    username: postgres
    password:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true

app:
  jwt:
    secret: "jkZC1dz35bKamDN5S7g2LoFZP5xMVjcouyOtfLSe4TK"
    expiration-ms: 900000
    refresh-expiration-ms: 604800000

server:
  port: 8080